runtime: nodejs20
instance_class: F1

handlers:
  - url: /(.*)
    static_files: build/\1
    upload: build/.*
    secure: always
    http_headers:
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY
      X-XSS-Protection: "1; mode=block"

automatic_scaling:
  min_instances: 1
  max_instances: 3
  target_cpu_utilization: 0.65
