runtime: nodejs20

handlers:
  - url: /static
    static_dir: build/static

  - url: /.*\.(js|css|png|jpg|jpeg|gif|svg|ico|json|txt|map)
    static_files: build/\0
    upload: build/.*

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
