steps:
  # 1. Copy .env file dari Cloud Storage
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://penitipan-hewan-config/.env", ".env"]
    dir: "backend"

  # 2. Build Docker image dari folder backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/penitipan-hewan-backend", "."]
    dir: "backend"

  # 3. Push image ke Container Registry (tag commit SHA)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/penitipan-hewan-backend:$COMMIT_SHA'
    id: 'push-image'

  # 4. Push image ke tag 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/penitipan-hewan-backend:latest'
    id: 'push-latest'

  # 5. Deploy ke Cloud Run dengan variabel dari file .env
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -a
        source ./backend/.env
        set +a

        gcloud run deploy penitipan-hewan-backend \
          --image gcr.io/$PROJECT_ID/penitipan-hewan-backend:$COMMIT_SHA \
          --region asia-southeast2 \
          --platform managed \
          --allow-unauthenticated \
          --port 5000 \
          --memory 1Gi \
          --cpu 1 \
          --max-instances 10 \
          --set-env-vars "NODE_ENV=production,PORT=5000,DB_NAME=${DB_NAME},DB_USERNAME=${DB_USERNAME},DB_PASSWORD=${DB_PASSWORD},DB_HOST=${DB_HOST},ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET},REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}"
    id: 'deploy-service'
    waitFor: ['push-image']

# Build timeout
timeout: '1200s'

# Mesin build yang lebih cepat
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
