steps:
  # 1. Salin file .env dari bucket ke folder backend
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", ".env"]
    dir: "backend"

  # 2. Build Docker image backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/penitipan-hewan-backend", "."]
    dir: "backend"

  # 3. Push Docker image ke Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/penitipan-hewan-backend"]
    dir: "backend"

  # 4. Deploy ke Cloud Run TANPA cloudsql socket (tidak pakai --add-cloudsql-instances)
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "penitipan-hewan-backend"
      - "--image"
      - "gcr.io/$PROJECT_ID/penitipan-hewan-backend"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--timeout"
      - "300"
      - "--set-env-vars"
      - |
        NODE_ENV=production,
        DB_NAME=${_DB_NAME},
        DB_USERNAME=${_DB_USERNAME},
        DB_PASSWORD=${_DB_PASSWORD},
        DB_HOST=${_DB_HOST},
        ACCESS_TOKEN_SECRET=${_ACCESS_TOKEN_SECRET},
        REFRESH_TOKEN_SECRET=${_REFRESH_TOKEN_SECRET}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _ENV: gs://tcc-hewan/.env                     # lokasi file .env kamu
  _REGION: us-central1                          # region Cloud Run
  _DB_NAME: hewan                              # nama database
  _DB_USERNAME: root                           # user database
  _DB_PASSWORD: penitipanhewan                  # password user
  _DB_HOST: 34.45.182.8                        # IP publik Cloud SQL
  _ACCESS_TOKEN_SECRET: penitipanhewanilegal205143
  _REFRESH_TOKEN_SECRET: penitipanhewanilegal143205
