steps:
    # 1. Build Docker image untuk backend
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", ".env"]
    dir: "backend"

  # 2. Build Docker image dari folder backend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/penitipan-hewan-backend", "."]
    dir: "backend"

  # 3. Push image ke Container Registry / Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/penitipan-hewan-backend"]

  # 4. Deploy ke Cloud Run dengan env vars langsung di-set
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "penitipan-hewan-backend",                   
        "--image",
        "gcr.io/$PROJECT_ID/penitipan-hewan-backend",
        "--region",
        "us-central1",                           
        "--platform",
        "managed",
        "--port",
        "5000",                                       
        "--allow-unauthenticated",
        "--set-env-vars",
        "NODE_ENV=production,PORT=5000,DB_NAME=hewan,DB_USERNAME=root,DB_PASSWORD=,DB_HOST=34.45.182.8,ACCESS_TOKEN_SECRET=penitipanhewanilegal205143,REFRESH_TOKEN_SECRET=penitipanhewanilegal143205"
      ]

# Logging hanya ke Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY
