steps:
  # 1. Install dependencies & build React
  - name: "node"
    entrypoint: bash
    dir: "frontend"
    args:
      - -c
      - |
        npm install
        npm run build

  # 2. Deploy ke App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    dir: "frontend"
    args: ["gcloud", "app", "deploy", "--quiet"]

# Logging ke Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY
